dom/microblog/mblog/urls.py
__author__ = 'Noitra'
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    # ex: /full/5/
    url(r'full/(?P<tweet_id>\d+)/$', views.detail, name='detail'),
)

dom/microblog/microblog/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^mblog/', include('mblog.urls', namespace='mblog')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

dom/microblog/mblog/models.py
from django.db import models

# Create your models here.
class Tweet(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=500)
    pub_date = models.DateTimeField('date published')
    def __unicode__(self):
        return self.title

dom/microblog/mblog/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404
from models import Tweet


def index(request):
    latest_tweet_list = Tweet.objects.all().order_by('-pub_date')
    context = {'latest_tweet_list': latest_tweet_list}
    return render(request, 'mblog/index.html', context)


def detail(request, tweet_id):
    tweet = get_object_or_404(Tweet, pk=tweet_id)
    return render(request, 'mblog/detail.html', {'tweet': tweet})

dom/microblog/mblog/templates/mblog/detail.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'mblog/style.css' %}" />

<div id='container'>
    <div id='header'>
    </div>
    <div id="menu">
        <ul>
            <li><a href="{% url 'mblog:index' %}">Strona Główna</a></li>
            <hr />
            <li><a href="/admin/">Dodaj wpis</a></li>
        </ul>
    </div>
    <div id="content">
        <h1 style="margin-top:0">{{ tweet.title }}</h1>
        <h3>Data wpisu: {{ tweet.pub_date }}</h3>
        <h3 style="margin-bottom: 0px;">Pełna treść:</h3>
        <p style="text-indent: 20px;margin-top: 0px;">{{ tweet.content }}</p>
    </div>
</div>

dom/microblog/mblog/templates/mblog/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'mblog/style.css' %}" />

<div id='container'>
    <div id='header'>
    </div>
    <div id="menu">
        <ul>
            <li><a href="{% url 'mblog:index' %}">Strona Główna</a></li>
            <hr />
            <li><a href="/admin/">Dodaj/Edytuj/Usuń wpis</a></li>
        </ul>
    </div>
    <div id="content">
        <h3>Wpisy:</h3>
        {% if latest_tweet_list %}
            <ul>
            {% for tweet in latest_tweet_list %}
                <li>
                    <hr>
                    <span style="font-weight: bold">Tytuł: </span><span style="font-style: italic">{{ tweet.title }}</span></br>
                    <span style="font-weight: bold">Data wpisu: </span>{{ tweet.pub_date }}</br>
                    <span style="font-weight: bold">Treść:</span>
                    <p style="text-indent: 20px;margin-top: 0px;">
                        {% if tweet.content|length  > 150 %}
                            {{ tweet.content|slice:":150" }}...
                        <a href="{% url 'mblog:detail' tweet.id %}">czytaj dalej</a></p>
                        {% else %}
                            {{ tweet.content }}</p>
                        {% endif %}
                    <hr />
                </li>
            {% endfor %}
            </ul>
        {% else %}
            <p>Niestety nie ma jeszcze żadnych wpisów :(</p>
        {% endif %}
    </div>
</div>